[custom]
;不要随意改变关键字，否则会导致出错

ruleset=🌍 全球直连,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/LocalAreaNetwork.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/GoogleCN.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/SteamCN.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/ChinaDomain.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/ChinaCompanyIp.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=🌍 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.list
ruleset=🌍 全球直连,[]GEOSITE,category-public-tracker
ruleset=🌍 全球直连,[]GEOIP,LAN,no-resolve
ruleset=🌍 全球直连,[]GEOIP,CN,no-resolve
ruleset=🚫 全球拦截,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/BanProgramAD.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/Apple.list
ruleset=👾 AI服务,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/AI.list
ruleset=📺 国外媒体,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/ProxyGFWlist.list
ruleset=✴️ 翻墙网站,https://raw.githubusercontent.com/ycy119744220/ClashRules/refs/heads/main/My.list
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]DIRECT`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`600,,50
custom_proxy_group=📺 国外媒体`select`[]🚀 节点选择`[]DIRECT`.*
custom_proxy_group=👾 AI服务`select`[]🚀 节点选择`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🍎 苹果服务`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🌍 全球直连`select`[]DIRECT`[]🚀 节点选择
custom_proxy_group=🚫 全球拦截`select`[]DIRECT`[]REJECT
custom_proxy_group=🍃 应用净化`select`[]DIRECT`[]REJECT
custom_proxy_group=✴️ 翻墙网站`select`[]🚀 节点选择`.*
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🌍 全球直连

enable_rule_generator=true
overwrite_original_rules=true
